[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vc_core = { path = "../vc_core" }
actix-web = "4.3"
serde = "1.0.160"
serde_json = "1.0.96"
rocksdb = "0.20.1"